const CountryList = [
  { id: 1, name: "United States" },
  { id: 2, name: "Canada" },
  { id: 3, name: "United Kingdom" },
  { id: 4, name: "Germany" },
  { id: 5, name: "France" },
  { id: 6, name: "Japan" },
  { id: 7, name: "Australia" },
  { id: 8, name: "Brazil" },
  { id: 9, name: "India" },
  { id: 10, name: "South Africa" },
  { id: 11, name: "Spain" },
  { id: 12, name: "Mexico" },
  { id: 13, name: "Italy" },
  { id: 14, name: "Russia" },
  { id: 15, name: "China" },
  { id: 16, name: "Argentina" },
  { id: 17, name: "Turkey" },
  { id: 18, name: "Sweden" },
  { id: 19, name: "Netherlands" },
  { id: 20, name: "South Korea" },
];
export default CountryList;
